### ISSUE TITLE
Attachment Name does not show Norwegian Characters

### ISSUE THREAD

**Issue by PrinceVarshney** [sendgrid/java-http-client#19] opened 2017-03-15 11:48 UTC
#### Issue Summary

I am new to SendGrid, I wanted to send a mail with attachment having Norwegian characters in the name. Receiver is receiving the mail but the name contains Å instead of Ø. Saw the Client class , it contains the change for UTF characters

sendgrid-java v3.1.0 is being used. Not using the java-http-client. I visited few related issues but was not able to get which api version include this change. Its urgent for me as we are going in production in two weeks.

Please help!

**Comment by thinkingserious** [comment] 2017-03-15 17:06
Hello @PrinceVarshney,

I believe you are asking for us to update the [dependency in sendgrid-java](https://github.com/sendgrid/sendgrid-java/blob/master/build.gradle#L48) to support v4.1.0 of this library. Correct?

If so, here is the ticket for that: https://github.com/sendgrid/sendgrid-java/pull/162 -- I will add your vote to that issue to grant it higher priority.

With Best Regards,

Elmer

**Comment by PrinceVarshney** [comment] 2017-03-15 18:25
Hei @thinkingserious 
I am not able to get why its converting Ø -->Å , because the Client.java class has the UTF-8 support then why  I am facing the issue.. ? Is this because of the dependency thats not included in sendgrid-java v3.1.0 ,I can externally include the dependency of httpClient if its required. But will it help. ? I need a urgent fix as we are moving in production in few days.

Please help!!

**Comment by thinkingserious** [comment] 2017-03-15 18:50
Hello @PrinceVarshney,

I'm not sure what is causing that issue, I am attempting to clarify with you.

Let me make sure my assumptions are correct:

1. You are using the sendgrid-java SDK v3.1.0.
2. I think that a similar issue was fixed with this PR: https://github.com/sendgrid/java-http-client/pull/5

Also, can you please provide me with the sample file so that I can try to re-create the issue?

Thanks!

Elmer

**Comment by PrinceVarshney** [comment] 2017-03-16 10:51
@thinkingserious 

Yeah I am using sendgrid-java SDK v3.1.0.

We are creating runtime content and the name of the pdf visible to the user is 
Pris og oppgjÃ¸rsvilkÃ¥r.pdf

that should be 
Pris og oppgjørsvilkår.pdf  


This is where I am attaching the file

Attachments attachments=new Attachments();
        Charset.forName("UTF-8").encode(attachmentName);
        attachments.setFilename(attachmentName);
        attachments.setType(type);
        attachments.setDisposition("attachment");
        attachments.setContent(Base64.encodeBase64String(attachment));
        List<Attachments> attachList = new ArrayList<Attachments>();
		attachList.add(attachments);
		emailDTO.setAttachment(attachList);


While sending it through sendgrid : 
Attached the file for the reference-
[sampleFile.txt](https://github.com/sendgrid/java-http-client/files/847454/sampleFile.txt)

**Comment by thinkingserious** [comment] 2017-03-16 16:30
Hello @PrinceVarshney,

I was unable to reproduce the error, here is the code I used:

```java
import com.sendgrid.*;

import java.io.IOException;
import java.util.HashMap;
import java.util.Map;

public class Example {

  public static Mail buildHelloEmail() throws IOException {
    Email from = new Email("dx@sendgrid.com");
    String subject = "Hello World from the SendGrid Java Library";
    Email to = new Email("elmer.thomas@sendgrid.com");
    Content content = new Content("text/plain", "some text here");
    Mail mail = new Mail(from, subject, to, content);

    Attachments attachments = new Attachments();
    attachments.setContent("TG9yZW0gaXBzdW0gZG9sb3Igc2l0IGFtZXQsIGNvbnNlY3RldHVyIGFkaXBpc2NpbmcgZWxpdC4gQ3JhcyBwdW12");
    attachments.setType("application/pdf");
    attachments.setFilename("Pris og oppgjørsvilkår.pdf");
    attachments.setDisposition("attachment");
    attachments.setContentId("Balance Sheet");
    mail.addAttachments(attachments);

    return mail;
  }

  public static void baselineExample() throws IOException {
    SendGrid sg = new SendGrid(System.getenv("SENDGRID_API_KEY"));
    Request request = new Request();
    Mail helloWorld = buildHelloEmail();
    try {
      request.method = Method.POST;
      request.endpoint = "mail/send";
      request.body = helloWorld.build();
      Response response = sg.api(request);
      System.out.println(response.statusCode);
    } catch (IOException ex) {
      throw ex;
    }
  }

  public static void main(String[] args) throws IOException {
    baselineExample();
  }
}
```

Perhaps the value in `attachmentName` is getting changed before you pass it into the `setFilename` function.

**Comment by PrinceVarshney** [comment] 2017-03-16 17:14
Hey @thinkingserious 
I hardcoded the value in the attachment name, then also I was facing the same error. You are using the same version of sendgrid-java. ?

**Comment by thinkingserious** [comment] 2017-03-16 17:16
@PrinceVarshney,

Yes, I am using the latest version 3.1.0.

Can you check the encoding on your source code editor?

**Comment by PrinceVarshney** [comment] 2017-03-16 17:58
@thinkingserious 

Will it matter. ? I think you are talking about eclipse. ?

Whats the use of below line ?

sg.addRequestHeader("X-Mock", "true");

**Comment by thinkingserious** [comment] 2017-03-16 17:59
That line can be ignored, it is for when we use our local testing server. I just tried without that line with the same result.

For Eclipse: http://stackoverflow.com/questions/9180981/how-to-support-utf-8-encoding-in-eclipse

**Comment by PrinceVarshney** [comment] 2017-03-16 18:11
My request in the logs is printed  correctly : 
"type":"application/pdf","filename":"Pris og oppgjørsvilkår.pdf","disposition":"attachment"}

so does the eclipse encoding will matter.. ?

**Comment by thinkingserious** [comment] 2017-03-16 18:15
I'm not sure.

Can you please try sending your test email to elmer.thomas@sendgrid.com?

**Comment by PrinceVarshney** [comment] 2017-03-16 19:58
@thinkingserious 

I have sent one mail on this id. One thing I observed that the issue is with MicrosoftOutlook only, in gmail its fine.

**Comment by thinkingserious** [comment] 2017-03-16 20:04
Hello @PrinceVarshney,

I have received the email correctly in GMail. Since the filename is correct on your server and in GMail, it appears the issue is with Outlook and that it might be a [known problem](https://answers.microsoft.com/en-us/msoffice/forum/msoffice_outlook-mso_other/outlook-wont-show-special-characters-norwegian/fe87d882-594e-425a-a117-8f7869e9223b).

I'm going to leave this issue open for further investigation. Perhaps there is some header that Microsoft Outlook requires to ensure UTF-0 encoding.

**Comment by PrinceVarshney** [comment] 2017-03-16 20:09
Hey @thinkingserious 

I need to have some workaround for the same, as most of the clients of our projects are using Outlook only.

**Comment by thinkingserious** [comment] 2017-03-17 17:28
Hello @PrinceVarshney,

I have added this to our backlog for further review.

**Comment by thinkingserious** [comment] 2017-03-17 18:00
Hi @PrinceVarshney,

Can you please try:

`attachments.setFilename("=?utf-8?Q?Pris=20og=20oppgj=C3=B8rsvilk=C3=A5r.pdf?=");`

Thanks!

Elmer

**Comment by PrinceVarshney** [comment] 2017-03-17 18:14
Hi @thinkingserious 

Will try this and will inform you regarding the same.

Thanks!!

**Comment by PrinceVarshney** [comment] 2017-03-17 20:09
Hey @thinkingserious 

This is not working. This is giving =utf-8QPris=20og=20oppgj=C3=B8rsvilk=C3=A5r.pdf

Thanks

**Comment by thinkingserious** [comment] 2017-03-17 20:24
Hello @PrinceVarshney,

What version of Outlook are you using?

**Comment by thinkingserious** [comment] 2017-03-17 20:28
@PrinceVarshney,

Can you email me with your Outlook email address so I can try sending a test to you?

**Comment by PrinceVarshney** [comment] 2017-03-17 20:30
@thinkingserious 
version of outlook : 14.0.7177.5000

**Comment by PrinceVarshney** [comment] 2017-03-17 20:33
@thinkingserious 
I have sent you a mail

**Comment by PrinceVarshney** [comment] 2017-03-17 20:51
@thinkingserious 

Hey Its working 

I attached this MimeUtility.encodeText("string", "UTF-8", "Q")
 while setting the attachmentName : 

mail.setAttachmentName(MimeUtility.encodeText("Pris og oppgjørsvilkår.pdf", "UTF-8", "Q"))

First we have to encode it as per Q-encoded
Thanks

**Comment by thinkingserious** [comment] 2017-03-17 20:54
@PrinceVarshney,

That's awesome and thanks for sharing the solution! I'm going to keep this ticket open so that we can add this to the SDK.

For your efforts, we would like to offer you some swag. Please fill out [this form](https://docs.google.com/forms/d/e/1FAIpQLSelP4uF-wGJebxVYq1DYw5WzHomEUauab3YiqrshyCkRs0fqw/viewform#start=invite) for us :)

**Comment by PrinceVarshney** [comment] 2017-03-17 21:00
@thinkingserious 

Thank you !! Will fill the form once outside office network :)

**Comment by deepapanwar** [comment] 2017-10-21 05:32
Can I pick this issue?

**Comment by thinkingserious** [comment] 2021-03-11 03:22
Since there has been no activity on this issue since March 1, 2020, we are closing this issue. Please feel free to reopen or create a new issue if you still require assistance. Thank you!

**Closed as completed by thinkingserious** 2021-03-11 03:22 UTC
Labels: type: community enhancement, status: help wanted, difficulty: medium, type: twilio enhancement
